---
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: 🐶 Ruff Linter
        language: system
        types: [python]
        entry: mise project:lint
        require_serial: true
        stages: [pre-commit, pre-push, manual]
      - id: pytest
        name: 🧪 Pytest
        language: system
        types: [python]
        entry: mise project:tests
        require_serial: true
        stages: [pre-commit, pre-push, manual]
