---
name: Typing

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: 🔍 Mise
        uses: jdx/mise-action@v2
      - name: 🏗 Install dependencies
        run: poetry install --no-interaction
      - name: 🚀 Run mypy
        run: poetry run mypy src tests
